spring.application.name: POC
consumerGroup: ${spring.application.name}-Consumer-Group

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=poc
    username: root
    password: root
logging:
  level:
    springframework:
      data:
        r2dbc: DEBUG

